version: '2'

volumes:
  streaming:
  fedora:
  work:
  solr:

services:
  fedora:
    image: avalonmediasystem/fedora:4.7.4
    volumes:
      - fedora:/data
    environment:
      - JAVA_OPTIONS=${JAVA_OPTIONS} -Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.home=/data
    ports:
      - "8984:8080"
  solr:
    image: solr:7.2.1-alpine
    ports:
      - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/config:/opt/solr/avalon_conf
    command: bash -ce "precreate-core avalon /opt/solr/avalon_conf; precreate-core hydra-test /opt/solr/avalon_conf; solr-foreground"
  matterhorn:
    image: avalonmediasystem/matterhorn
    volumes:
      - ./masterfiles:/masterfiles
      - streaming:/streamfiles
      - work:/work
    ports:
      - "8080:8080"
  hls:
    image: avalonmediasystem/nginx
    volumes:
      - streaming:/data
    ports:
       - "8880:80"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  avalon:
    image: avalonmediasystem/avalon:6.x-dev
    command: "/rails_init-dev.sh"
    depends_on:
      - fedora
      - solr
      - redis
    environment:
      - APP_NAME=avalon
      - ASSET_HOST=http://localhost:3000
      - AVALON_BRANCH=develop
      - AVALON_DB_PASSWORD=avalondb
      - SETTINGS__DOMAIN=http://localhost:3000
      - CONTROLLED_VOCABULARY=config/controlled_vocabulary.yml
      - SETTINGS__DROPBOX__PATH=/masterfiles
      - SETTINGS__DROPBOX__UPLOAD_URI=./masterfiles
      - EMAIL_COMMENTS
      - EMAIL_NOTIFICATION
      - EMAIL_SUPPORT
      - FEDORA_BASE_PATH
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY=delete
      - MATTERHORN_URL=http://matterhorn_system_account:CHANGE_ME@matterhorn:8080/
      - SETTINGS__MATTERHORN__MEDIA_PATH=/masterfiles
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=development
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SECRET_KEY_BASE=abcd
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=http://solr:8983/solr/avalon
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__STREAMING__STREAM_DEFAULT_QUALITY=medium
      - SETTINGS__STREAMING__HTTP_BASE=http://localhost:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
    volumes:
      - ./masterfiles:/masterfiles
      - ./gems:/home/app/gems
      - .:/home/app/avalon
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
  avalon-test:
    image: avalonmediasystem/avalon:6.x-dev
    command: "/rails_init-dev.sh"
    depends_on:
      - fedora
      - solr
      - redis
    environment:
      - RAILS_ENV=test
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest/test
      - SOLR_URL=http://solr:8983/solr/hydra-test
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - FFMPEG_PATH=/usr/bin/ffmpeg
    volumes:
      - ./masterfiles:/masterfiles
      - ./gems:/home/app/gems
      - .:/home/app/avalon
